# fastagent.config.yaml

servers:
  drift-server:
    transport: stdio
    # Launch drift-server via Python in unbuffered mode so JSON‐RPC messages flow correctly
    command: python
    args:
      - -u
      - server.py

# Your model defaults (unchanged)
default_model: generic.llama3.1
generic:
  api_key: ollama       # placeholder
  base_url: http://localhost:11434/v1
